### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by ikhwan12** [codeslake/IFAN#10]
Hi @HyeongseokSon1 ,

I have an issue by running the latest code using this command :
`python run.py --mode IFAN --network IFAN --config config_IFAN --data DPDD --ckpt_abs_name ckpt/IFAN.pytorch --cpu --data_offset ./test --output_offset ./test_out`

Basically I would like to test my 1 .jpg image and store in `./test`

The error is shown like this:
![Capture](https://user-images.githubusercontent.com/16043445/173797077-91af08eb-1b0f-477c-8bd2-8e415db0faf1.PNG)

Here is my directory list:
![file](https://user-images.githubusercontent.com/16043445/173797149-d6b97cc4-90ba-4fbd-990b-f64fed41bbaf.PNG)

Do you know what is the problem ? or maybe I am doing wrong ?

**Comment by codeslake** [comment]
Hi, @ikhwan12!
I believe the error is due to the misplaced input image.
Please try the following steps.

1. Create a random folder `IFAN/test/random`.
    * the random folder is described in [here](https://github.com/codeslake/IFAN/wiki/Training-&-Testing-Details) (Testing/options/`--data`).
3. Place your image inside the random folder (*eg*, `IFAN/test/random/1.jpg`).
4. Run the following command:
    ```
    python run.py --mode IFAN --network IFAN --config config_IFAN --data random --ckpt_abs_name ckpt/IFAN.pytorch --cpu -- 
    data_offset ./test --output_offset ./test_out
    ```

**Comment by codeslake** [comment]
Hi, @ikhwan12.

Thank you for pointing this out!
There was a bug for loading images when the inputs are placed within the project folder.

I've just updated the code. Please pull and check whether it is working ok.

**Comment by ikhwan12** [comment]
Hi @codeslake 
Thank you for fixing the code.
Now it works.
