### ISSUE TITLE
Missing configuration file

### ISSUE THREAD

**Issue by windStringer** [codeslake/IFAN#12]
Traceback (most recent call last):
  File "D:/python/SCI/IFAN-main/IFAN-main/run.py", line 308, in <module>
    with open('{}/config.txt'.format(config.LOG_DIR.config)) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Bean/logs/junyonglee\\IFAN_CVPR2021\\IFAN\\config/config.txt'
Laoding Config for evaluation

**Comment by codeslake** [comment]
You need to change the offset path for logging dir.

Refer [here](https://github.com/codeslake/IFAN/wiki/Log-Details).

**Comment by BBetteroff** [comment]
In predict.py:
 ModuleNotFoundError: No module named 'cog'

**Comment by codeslake** [comment]
predict.py is for the [demo](https://replicate.com/codeslake/ifan-defocus-deblur).

You need to run the code using commands [here](https://github.com/codeslake/IFAN#testing-models-of-cvpr-2021)..

**Comment by windStringer** [comment]
sincere thanks! My problem has been solved. Your article is very well written, I wish the research success











在 2022-09-27 16:27:19，"Junyong Lee" ***@***.***> 写道：

Closed #12 as completed.
