### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by wangzhupi** [codeslake/IFAN#17]
when I run run.py this error happen , i have run this code step by step i  have no idea with this problem ,can somebody help me plz, thx

`Traceback (most recent call last):
  File "run.py", line 358, in <module>
    eval(config)
  File "/home/ubuntu01/Templates/IFAN1/IFAN/eval.py", line 197, in eval
    eval_quan_qual(config)
  File "/home/ubuntu01/Templates/IFAN1/IFAN/eval.py", line 182, in eval_quan_qual
    total_itr_time = total_itr_time / time_norm
ZeroDivisionError: division by zero`

**Comment by codeslake** [comment]
Hi, how did you setup your test images? Also, would your share your running script?

**Comment by codeslake** [comment]
Closing the issue. Please reopen this if you still have the problem.

**Comment by wangzhupi** [comment]
> Closing the issue. Please reopen this if you still have the problem.

I have solved this problem, anywway thanks for your reply

**Comment by YDB04234** [comment]
Bro，how do you solute it ,I also encountered this problem.
