### ISSUE TITLE
Possible syntax error in trainer.py

### ISSUE THREAD

**Issue by sreeragiyer** [codeslake/IFAN#2]
Hi, 

I faced `config` is undefined while trying to train the model. It looks like line 298 in https://github.com/codeslake/IFAN/blob/main/models/trainers/trainer.py should be `self.config.mode` instead of `config.mode`

edit: 278->298

**Comment by codeslake** [comment]
Hi, 

`config.mode` can also be referred, as `config` is passed through the `init` function.
Can you paste the exact error message?

**Comment by codeslake** [comment]
Hi, `config.mode` line 298 can be a problem. I've updated the repository.
Can you pull the repo and try the training procedure again?

**Comment by sreeragiyer** [comment]
yes, that resolves the issue.
