### ISSUE TITLE
Any chance make script demo more user friendly?

### ISSUE THREAD

**Issue by netrunner-exe** [codeslake/IFAN#4]
Thank you for this very interesting project. I would like to ask you to add an easier way to implement scripts - something like `python run.py --input_path --output_path`. - add ability to be able to specify the folder with the incoming image and the folder with the result. I think when there will be a full demo then more people will pay attention to this project, unfortunately, not everyone uses Google Collab.

**Comment by codeslake** [comment]
Hi, thank you for the suggestion!

I will try to provide options to pass paths for the input and output directories.

**Comment by codeslake** [comment]
Not yet. Thanks for the reminder though :)
I will try one in next few days.
